Skip mac build

diff --git a/.github/workflows/build-and-sign.yml b/.github/workflows/build-and-sign.yml
--- a/.github/workflows/build-and-sign.yml
+++ b/.github/workflows/build-and-sign.yml
@@ -103,21 +103,22 @@ jobs:
       run: |
         if [ ! -r docker/base-bionic-amd64.tar.xz ]; then
             echo "Argh - caching only works for push and pull events. See https://github.com/actions/cache/issues/63"
-            vendor/gitian-builder/bin/make-base-vm --docker --suite bionic
+            #vendor/gitian-builder/bin/make-base-vm --docker --suite bionic
         fi
     - name: Build and Sign
       run: |
         #docker load -i docker/base-bionic-amd64.tar.xz
         sudo apt-get install ruby
         export GNUPGHOME=`pwd`/.gpghome
-        echo ${{ secrets.PGP_PASSPHRASE }} 1>&3 \
-          | ./run-gitian -b -s BitShares-Gitian-Auto-Build-Signer \
-                         -O osx -p "gpg --passphrase-fd 3" \
-                         ${{ github.event.deployment.payload.coreversion }} \
-                         -j 1 \
-          || ( echo Install log: && cat vendor/gitian-builder/var/install.log \
-               && echo Build log: && cat vendor/gitian-builder/var/build.log \
-               && false )
+        echo "Skipping Mac build due to missing SDK"
+        #echo ${{ secrets.PGP_PASSPHRASE }} 1>&3 \
+        #  | ./run-gitian -b -s BitShares-Gitian-Auto-Build-Signer \
+        #                 -O osx -p "gpg --passphrase-fd 3" \
+        #                 ${{ github.event.deployment.payload.coreversion }} \
+        #                 -j 1 \
+        #  || ( echo Install log: && cat vendor/gitian-builder/var/install.log \
+        #       && echo Build log: && cat vendor/gitian-builder/var/build.log \
+        #       && false )
     - name: Upload build artifacts
       uses: actions/upload-artifact@master
       with:
